### ISSUE TITLE
CS61C Su20 PPT

### ISSUE THREAD

**Issue by ajwwja777** [SMS-Derfflinger/self-learning#1]
Hi there,

I noticed that you have a few CS61C Su20 PPT presentations in your repository. I would be very grateful if you could share the complete version with me.

Thank you very much for your help!

Best regards,
Jiaan Wang

(QQ: 1741440971)

**Comment by SMS-Derfflinger** [comment]
Hi Jiaan Wang,

Thank you for reaching out! Unfortunately, I don't have the complete set of those presentations. However, you can find the complete CS61C Su20 PowerPoint presentations in repository at https://github.com/PKUFlyingPig/CS61C-summer20. 

Additionally, if you're interested, I personally found that the course quality for Fa20 was even higher. You can access all the resources for that semester at this repository https://github.com/SMS-Derfflinger/self-learning/tree/master/CS61C/fa20.

Let me know if you need any further assistance!

Best regards,
Jinning Na
